# A first worflow to play around with the editor
name: My First Workflow
on:
  push:
    branches:
      - main
jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: echo "Hello World from ${{ github.actor }}."
             echo "Current Branch is ${{ github.ref }}."
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run tree command on the just checked-out repository
        run: tree
